Fix an "undefined method" error with rubygems >= 3.2.33
voxpupuli/hiera-eyaml pull request #327
Opened 2022-02-17 04:54 UTC by davidsansome

https://github.com/rubygems/rubygems/commit/ae3980eed01ed17c186ceb4094adef185864512e changed `Gem::Specification.latest_specs` to return `Gem::StubSpecification` objects instead of `Gem::Specification` objects. That broke hiera-eyaml which expects the objects to have a `dependencies` method:

```
$ eyaml
Traceback (most recent call last):
	7: from /usr/local/bin/eyaml:23:in `<main>'
	6: from /usr/local/bin/eyaml:23:in `load'
	5: from /var/lib/gems/2.7.0/gems/hiera-eyaml-3.2.2/bin/eyaml:10:in `<top (required)>'
	4: from /var/lib/gems/2.7.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:31:in `find'
	3: from /var/lib/gems/2.7.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:31:in `each'
	2: from /var/lib/gems/2.7.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:34:in `block in find'
	1: from /var/lib/gems/2.7.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:34:in `each'
/var/lib/gems/2.7.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:37:in `block (2 levels) in find': undefined method `dependencies' for #<Gem::StubSpecification:0x0000559da19dd520> (NoMethodError)
```

2022-02-17 05:03 UTC, smortex requested changes

2022-02-17 05:03 UTC, smortex commented on lib/hiera/backend/eyaml/plugins.rb
> +              spec = Gem::VERSION >= "3.2.33" ? stub.to_spec : stub
```
irb(main):002:0> Gem::VERSION
=> "3.0.8"
irb(main):003:0> Gem::VERSION.class
=> String
```

Comparing string is probably not safe:

```
irb(main):004:0> "3.10.0" < "3.2.33"
=> true
irb(main):005:0> Gem::Version.new("3.10.0") < Gem::Version.new("3.2.33")
=> false
```

```suggestion
              spec = Gem::Version.new(Gem::VERSION) >= Gem::Version.new("3.2.33") ? stub.to_spec : stub
```

2022-02-17 05:12 UTC, davidsansome commented on lib/hiera/backend/eyaml/plugins.rb
> +              spec = Gem::VERSION >= "3.2.33" ? stub.to_spec : stub
Done, thanks! I've also fixed the other version comparisons in this file too.

2022-02-17 06:51 UTC, smortex approved these changes
Looks fine

2022-02-17 07:02 UTC, smortex commented on lib/hiera/backend/eyaml/plugins.rb
> +              spec = gem_version >= Gem::Version.new("3.2.33") ? stub.to_spec : stub
https://github.com/rubygems/rubygems/commit/ae3980eed01ed17c186ceb4094adef185864512e is unclean: the change seems to be part of `>= 2.3.0 < 3.0.0` ([bundler-v2.3.7](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.7) [bundler-v2.3.6](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.6) [bundler-v2.3.5](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.5) [bundler-v2.3.4](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.4) [bundler-v2.3.3](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.3) [bundler-v2.3.2](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.2) [bundler-v2.3.1](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.1) [bundler-v2.3.0](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.0)) and `>= 3.3.0` ([v3.3.7](https://github.com/rubygems/rubygems/releases/tag/v3.3.7) [v3.3.6](https://github.com/rubygems/rubygems/releases/tag/v3.3.6) [v3.3.5](https://github.com/rubygems/rubygems/releases/tag/v3.3.5) [v3.3.4](https://github.com/rubygems/rubygems/releases/tag/v3.3.4) [v3.3.3](https://github.com/rubygems/rubygems/releases/tag/v3.3.3) [v3.3.2](https://github.com/rubygems/rubygems/releases/tag/v3.3.2) [v3.3.1](https://github.com/rubygems/rubygems/releases/tag/v3.3.1) [v3.3.0](https://github.com/rubygems/rubygems/releases/tag/v3.3.0)), but the release notes of these tags seems to mention the PR only for v3.3.0 :confused: 

Can you please double-check that comparing with 3.2.33 is the right thing to do?  Thanks!

2022-02-17 10:23 UTC, davidsansome commented on lib/hiera/backend/eyaml/plugins.rb
> +              spec = gem_version >= Gem::Version.new("3.2.33") ? stub.to_spec : stub
Oops you're right - it's v3.3.0 not v3.2.33. I just saw the v3.2.33 changelog commit went into master after https://github.com/rubygems/rubygems/commit/ae3980eed01ed17c186ceb4094adef185864512e, but I didn't realise that was on a separate branch.

I've updated this check to v3.3.0 now!

2022-02-17 16:32 UTC, smortex commented on lib/hiera/backend/eyaml/plugins.rb
> +              spec = gem_version >= Gem::Version.new("3.2.33") ? stub.to_spec : stub
Thanks!

2022-02-23 02:39 UTC, davidsansome commented
> LGTM!

Thanks for the review smortex!
Any idea what else I need to do to get this merged? @bastelfreak?

2022-02-23 08:31 UTC, merged

2022-03-09 13:12 UTC, robeke commented
I was hopeful this would resolve the issue but still unable to use with Manjaro Linux:
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.5
  - RUBY VERSION: 3.0.3 (2021-11-24 patchlevel 157) [x86_64-linux]

Result of running eyaml -h 
``/home/xxxxx/.local/share/gem/ruby/3.0.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:37:in `block (2 levels) in find': undefined method `dependencies' for #<Gem::StubSpecification:0x000055af4d3bd100 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @loaded_from="/usr/lib/ruby/gems/3.0.0/specifications/default/abbrev-0.1.0.gemspec", @data=#<Gem::StubSpecification::StubLine:0x000055af4d3bc188 @name="abbrev", @version=#<Gem::Version "0.1.0">, @platform="ruby", @extensions=[], @full_name="abbrev-0.1.0", @require_paths=["lib"]>, @name=nil, @spec=nil, @base_dir="/usr/lib/ruby/gems/3.0.0", @gems_dir="/usr/lib/ruby/gems/3.0.0/gems", @default_gem=true> (NoMethodError)
	from /home/xxxxx/.local/share/gem/ruby/3.0.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:34:in `each'
	from /home/xxxxx/.local/share/gem/ruby/3.0.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:34:in `block in find'
	from /home/xxxxx/.local/share/gem/ruby/3.0.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:31:in `each'
	from /home/xxxxx/.local/share/gem/ruby/3.0.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:31:in `find'
	from /home/xxxxx/.local/share/gem/ruby/3.0.0/gems/hiera-eyaml-3.2.2/bin/eyaml:10:in `<top (required)>'
	from /home/xxxxx/.local/share/gem/ruby/3.0.0/bin/eyaml:25:in `load'
	from /home/xxxxx/.local/share/gem/ruby/3.0.0/bin/eyaml:25:in `<main>'``