Add aptitude to installation methods
voxpupuli/hiera-eyaml pull request #338
Opened 2023-01-13 10:57 UTC by AntoineSebert

Specifies the command to install `hiera-eyaml` using the aptitude package manager, typically on Ubuntu OS.
The Ubuntu version requirement has been obtained from: https://packages.ubuntu.com/search?keywords=hiera-eyaml&searchon=names&suite=all&section=all
The original installation method using `gem` has been in a "RubyGems" section.

2023-01-13 23:45 UTC, kenyon requested changes

2023-01-13 23:45 UTC, kenyon commented on README.md
> +#### Aptitude (Ubuntu 18.04+)
The heading says `aptitude` but the command used is `apt`.

```suggestion
#### Apt (Ubuntu 18.04+)
```

2023-01-14 07:49 UTC, AntoineSebert commented on README.md
> +#### Aptitude (Ubuntu 18.04+)
It's a typo, my bad

2023-01-14 08:20 UTC, kenyon approved these changes

2023-01-14 19:41 UTC, merged